import os
import pickle
import numpy as np
import pandas as pd
from typing import TypedDict, List, Annotated, Dict
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from dotenv import load_dotenv

load_dotenv()

# --- State Definition ---
class AgentState(TypedDict):
    property_details: Dict
    predicted_price: float
    market_context: str
    advisory_report: str
    steps: List[str]

# --- Helper Functions ---
def load_ml_artifacts():
    try:
        model = pickle.load(open('models/trained_model.pkl', 'rb'))
        label_encoder = pickle.load(open('models/label_encoder.pkl', 'rb'))
        columns = pickle.load(open('models/columns.pkl', 'rb'))
        return model, label_encoder, columns
    except Exception as e:
        print(f"Error loading models: {e}")
        return None, None, None

# --- Node Definitions ---

def valuation_node(state: AgentState):
    print("--- NODE: Valuation ---")
    details = state['property_details']
    model, le, cols = load_ml_artifacts()
    
    if not model:
        return {**state, "predicted_price": 0.0, "steps": state['steps'] + ["Failed to load ML model"]}
    
    try:
        location = details.get('location', 'other')
        if location in le.classes_:
            loc_encoded = le.transform([location])[0]
        else:
            loc_encoded = le.transform(['other'])[0]
            
        features = np.array([[
            loc_encoded, 
            details.get('total_sqft', 1000), 
            details.get('bath', 2), 
            details.get('bhk', 2)
        ]])
        
        prediction = model.predict(features)[0]
        return {
            **state, 
            "predicted_price": prediction, 
            "steps": state['steps'] + [f"Valuation completed: ₹{prediction:.2f} Lakhs"]
        }
    except Exception as e:
        return {**state, "predicted_price": 0.0, "steps": state['steps'] + [f"Valuation error: {str(e)}"]}

def market_research_node(state: AgentState):
    print("--- NODE: Market Research ---")
    location = state['property_details'].get('location', 'Bangalore')
    
    try:
        # Use local HuggingFace embeddings
        embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
        vectorstore = Chroma(persist_directory="./chroma_db", embedding_function=embeddings)
        
        # Search for location-specific info and general info
        results = vectorstore.similarity_search(location, k=2)
        general_results = vectorstore.similarity_search("Investment Advice Regulation", k=2)
        
        context = "\n".join([doc.page_content for doc in results + general_results])
        return {
            **state, 
            "market_context": context, 
            "steps": state['steps'] + [f"Retrieved market trends for {location}"]
        }
    except Exception as e:
        return {
            **state, 
            "market_context": "No specific market data available.", 
            "steps": state['steps'] + [f"Research error: {str(e)}"]
        }

def advisory_node(state: AgentState):
    print("--- NODE: Advisory Reasoning ---")
    # Using ChatGroq with Llama 3.3 70B for high-quality reasoning
    llm = ChatGroq(model_name="llama-3.3-70b-versatile", temperature=0.1)
    
    details = state['property_details']
    price = state['predicted_price']
    context = state['market_context']
    
    prompt = f"""
    You are an expert Real Estate Investment Advisor for the Bangalore market.
    
    Property Details:
    - Location: {details.get('location')}
    - Size: {details.get('total_sqft')} sqft
    - Configuration: {details.get('bhk')} BHK, {details.get('bath')} Bath
    - Predicted Market Value: ₹{price:.2f} Lakhs
    
    Market Context:
    {context}
    
    Task:
    Generate a structured advisory report for a potential investor. Include the following sections:
    1. SUMMARY: A brief overview of the property's value proposition.
    2. COMPS: Briefly mention how this property compares to the micro-market based on context.
    3. ACTION: Clear "Buy", "Hold", or "Invest" recommendation with reasoning.
    4. DISCLAIMER: Standard financial/legal notice.
    
    Guidelines:
    - Base your advice on the predicted price and retrieved market trends.
    - Be professional and data-driven.
    - Reduce hallucinations: if data is missing, state it clearly.
    """
    
    response = llm.invoke(prompt)
    return {
        **state, 
        "advisory_report": response.content, 
        "steps": state['steps'] + ["Advisory report generated by AI"]
    }

# --- Build the Graph ---

builder = StateGraph(AgentState)

builder.add_node("valuation", valuation_node)
builder.add_node("research", market_research_node)
builder.add_node("advisory", advisory_node)

builder.set_entry_point("valuation")
builder.add_edge("valuation", "research")
builder.add_edge("research", "advisory")
builder.add_edge("advisory", END)

# Compile
property_agent = builder.compile()

def get_advisory(details: Dict):
    initial_state = {
        "property_details": details,
        "predicted_price": 0.0,
        "market_context": "",
        "advisory_report": "",
        "steps": []
    }
    return property_agent.invoke(initial_state)

if __name__ == "__main__":
    # Test
    test_details = {"location": "Whitefield", "total_sqft": 1200, "bath": 2, "bhk": 3}
    result = get_advisory(test_details)
    print("\nFINAL REPORT:\n")
    print(result['advisory_report'])
